apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-connection-check
spec:
  schedule: "*/50 * * * *"  # Every 50 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: curlimages/curl:latest
            args:
            - curl
            - -f
            - http://svc-quake-watch:5000/
          restartPolicy: OnFailure