apiVersion: apps/v1
kind: Deployment
metadata:
  name: quake-watch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quake-watch
  template:
    metadata:
      labels:
        app: quake-watch
    spec:
      containers:
      - name: quake-watch-container
        image: lironyo98/flask_quakeqatch:0.2.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: flask-config
          - secretRef:
              name: flask-secret

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10